#!/usr/bin/env python3
"""Derive hostfakesplit_alt from zapret2's own hostfakesplit().

nfqws1 `--dpi-desync-hostfakesplit-mod=altorder=1` sends: before_host, FAKE host, after_host, REAL host.
Stock zapret2 hostfakesplit sends: before, fake1, REAL host, fake2, after. The alt function is generated by
re-ordering blocks of the stock code, so it follows zapret2 updates automatically. If zapret2 restructures the
function so the anchors below are not found, generation raises and the sync job fails (no broken release).
"""
import re, sys

class LuaGenError(RuntimeError):
    pass

def _find(src, pat, lo, hi, what):
    for i in range(lo, hi + 1):
        if re.search(pat, src[i - 1]):
            return i
    raise LuaGenError('hostfakesplit anchor not found: %s (zapret2 changed the function?)' % what)

def generate(src_path, dst_path):
    src = open(src_path, encoding='utf-8').read().split('\n')
    start = next((i for i, l in enumerate(src, 1) if l.startswith('function hostfakesplit(ctx, desync)')), None)
    if start is None:
        raise LuaGenError('function hostfakesplit not found in %s' % src_path)
    end = next(i for i in range(start, len(src)) if src[i - 1] == 'end')

    fake1 = _find(src, r'if not desync\.arg\.nofake1', start, end, 'fake1 block')
    a_end = fake1 + 3
    if src[a_end - 1].strip() != 'end':
        raise LuaGenError('fake1 block layout changed (line %d is %r)' % (a_end, src[a_end - 1]))
    c_beg = _find(src, r'local midhost$', start, end, 'midhost block')
    d_beg = _find(src, r'if not desync\.arg\.nofake2', start, end, 'fake2 block')
    e_beg = _find(src, r'local disorder_after_pos', start, end, 'real-host block')
    e_end = _find(src, r'pos\[2\], opts_orig\) then return VERDICT_PASS end', start, end, 'real-host send')
    if not (a_end < c_beg < d_beg < e_beg < e_end < end):
        raise LuaGenError('hostfakesplit block order changed')

    head = src[start - 1:a_end]
    C = src[c_beg - 1:d_beg - 1]
    E = src[e_beg - 1:e_end]
    tail = src[e_end:end]
    head[0] = 'function hostfakesplit_alt(ctx, desync)'
    out = ['-- generated by tools/make_lua.py from zapret2 lua/zapret-antidpi.lua hostfakesplit(); do not edit',
           '-- emulates nfqws1 --dpi-desync-hostfakesplit-mod=altorder=1 : before_host, fake host, after_host, real host',
           '-- args: same as hostfakesplit (host, midhost, fooling, ip_id, repeats ...); nofake1 is supported',
           ''] + head + E + [''] + C + tail
    open(dst_path, 'w', encoding='utf-8', newline='\n').write('\n'.join(out).replace('hostfakesplit:', 'hostfakesplit_alt:') + '\n')

if __name__ == '__main__':
    generate(sys.argv[1], sys.argv[2])
